defmodule Tet.Retention.Enforcer do
  @moduledoc """
  Retention enforcement for TET data lifecycle — BD-0037.

  Provides three operations:

  1. **Pre-deletion checks** — `check_before_delete/3` returns `:ok` if
     deletion is allowed or `{:error, :audit_protected}` if the record
     requires explicit acknowledgement.

  2. **Audit acknowledgement** — `acknowledge_delete/3` generates a
     time-limited token that must be presented to complete deletion of
     audit-protected records.

  3. **Cleanup enforcement** — `enforce/4` scans a session's data for a
     given type and removes records that exceed TTL or max_count, skipping
     records that cannot be pruned under the current policy.

  The enforcer never calls the store directly — it accepts a store adapter
  and session data as arguments, making it testable without starting a
  database or GenServer.
  """

  alias Tet.Retention.{Class, Policy}

  @typedoc """
  Result of a pre-deletion eligibility check.
  """
  @type check_result :: :ok | {:error, :audit_protected} | {:error, :permanent} | {:error, term()}

  @typedoc """
  Acknowledgement token for audit-protected deletions.

  Generated by `acknowledge_delete/3` and consumed by `acknowledged_delete/4`.
  Tokens are opaque and time-stamped but not validated against a central
  store — they encode the class, record ID, and a nonce for basic integrity.
  """
  @type ack_token :: Policy.ack_token()

  @doc """
  Checks whether a record can be deleted under the given policy.

  Returns `:ok` if deletion is allowed (record is not audit-protected and
  not permanent), or `{:error, reason}` if the record is protected.

  ## Examples

      iex> policy = elem(Tet.Retention.Policy.new([]), 1)
      iex> Tet.Retention.Enforcer.check_before_delete(policy, :checkpoint, "cp_001")
      :ok

      iex> Tet.Retention.Enforcer.check_before_delete(policy, :approval, "ap_001")
      {:error, :permanent}

      iex> Tet.Retention.Enforcer.check_before_delete(policy, :error_log, "err_001")
      {:error, :audit_protected}
  """
  @spec check_before_delete(Policy.t(), Policy.data_type(), binary()) :: check_result()
  def check_before_delete(%Policy{} = policy, data_type, _record_id)
      when is_atom(data_type) do
    cond do
      Policy.audit_protected?(policy, data_type) and
          class_for(policy, data_type).name == :permanent ->
        {:error, :permanent}

      Policy.audit_protected?(policy, data_type) ->
        {:error, :audit_protected}

      not Policy.deletable?(policy, data_type) ->
        {:error, :not_deletable}

      true ->
        :ok
    end
  end

  @doc """
  Generates an acknowledgement token for deleting an audit-protected record.

  The caller must present this token to `acknowledged_delete/4` to complete
  the deletion. This two-step flow ensures the operator (or calling code)
  explicitly acknowledges the audit implications of the deletion.

  Returns `{:ok, ack_token}` or:
  - `{:error, :permanent}` — permanent records cannot be deleted at all
  - `{:error, :not_audit_protected}` — no token needed (not audit-protected)

  Accepts opts:
  - `:actor` — identity of the entity acknowledging the deletion (default: "system")

  ## Examples

      iex> policy = elem(Tet.Retention.Policy.new([]), 1)
      iex> {:ok, token} = Tet.Retention.Enforcer.acknowledge_delete(policy, :error_log, "err_001", actor: "ops_user")
      iex> is_binary(token)
      true

      iex> Tet.Retention.Enforcer.acknowledge_delete(policy, :checkpoint, "cp_001")
      {:error, :not_audit_protected}
  """
  @spec acknowledge_delete(Policy.t(), Policy.data_type(), binary(), keyword()) ::
          {:ok, ack_token()} | {:error, term()}
  def acknowledge_delete(%Policy{} = policy, data_type, record_id, opts \\ [])
      when is_atom(data_type) and is_binary(record_id) and is_list(opts) do
    if Policy.audit_protected?(policy, data_type) do
      class = Policy.class_for(policy, data_type)

      if class.name == :permanent do
        {:error, :permanent}
      else
        token = Policy.generate_ack_token(policy, data_type, record_id, opts)
        {:ok, token}
      end
    else
      {:error, :not_audit_protected}
    end
  end

  @doc """
  Confirms that an acknowledgement token is valid and proceeds with deletion
  eligibility.

  Validates that:
  1. The data type is audit-protected
  2. The data type is not permanent (permanent records cannot be deleted)
  3. The token was generated by `acknowledge_delete/4` for this class and record ID

  Returns `:ok` if the token is valid, `{:error, reason}` otherwise.

  ## Examples

      iex> policy = elem(Tet.Retention.Policy.new([]), 1)
      iex> {:ok, token} = Tet.Retention.Enforcer.acknowledge_delete(policy, :error_log, "err_001")
      iex> Tet.Retention.Enforcer.acknowledged_delete(policy, :error_log, "err_001", token)
      :ok

      iex> Tet.Retention.Enforcer.acknowledged_delete(policy, :error_log, "err_001", "bad_token")
      {:error, :invalid_ack_token}
  """
  @spec acknowledged_delete(Policy.t(), Policy.data_type(), binary(), ack_token()) ::
          :ok | {:error, term()}
  def acknowledged_delete(%Policy{} = policy, data_type, record_id, token)
      when is_atom(data_type) and is_binary(record_id) and is_binary(token) do
    # Re-check that the data type is audit-protected and not permanent
    if Policy.audit_protected?(policy, data_type) do
      class = Policy.class_for(policy, data_type)

      if class.name == :permanent do
        {:error, :permanent}
      else
        # Decode token and verify HMAC
        verify_ack_token(policy, data_type, record_id, token)
      end
    else
      {:error, :not_audit_protected}
    end
  end

  @doc """
  Returns records that exceed the retention policy for a given data type and
  session, but **never** returns audit-protected or permanent records.

  Takes an enumerable of records (each must be a map/struct with `:created_at`
  and optionally `:id`) and returns those that are eligible for deletion.

  A record is eligible if:
  1. Its data type is deletable under the policy (not audit-critical/permanent)
  2. Its age exceeds the class TTL (if TTL is set)
  3. The count of records exceeds the class max_count (if max_count is set)

  For bounded-count eviction, the oldest records beyond the limit are
  returned. Records are returned in oldest-first order.

  ## Examples

      iex> policy = elem(Tet.Retention.Policy.new([]), 1)
      iex> records = [
      ...>   %{id: "old", created_at: ~U[2020-01-01 00:00:00Z]},
      ...>   %{id: "new", created_at: ~U[2025-01-01 00:00:00Z]}
      ...> ]
      iex> Tet.Retention.Enforcer.expired_records(policy, :checkpoint, records)
      {:ok, [%{id: "old"}]}
  """
  @spec expired_records(Policy.t(), Policy.data_type(), [map()]) ::
          {:ok, [map()]} | {:error, term()}
  def expired_records(%Policy{} = policy, data_type, records)
      when is_atom(data_type) and is_list(records) do
    # Never return audit-protected records
    if Policy.audit_protected?(policy, data_type) do
      {:ok, []}
    else
      class = Policy.class_for(policy, data_type)
      now = DateTime.utc_now()

      # Sort oldest-first — normalize timestamps to DateTime first
      sorted =
        records
        |> Enum.map(&normalize_created_at/1)
        |> Enum.sort_by(& &1.created_at, DateTime)

      # Step 1: Find records expired by TTL
      ttl_expired = expired_by_ttl(sorted, class, now)

      # Step 2: After removing TTL-expired records, check if remaining exceed max_count
      ttl_expired_ids = MapSet.new(ttl_expired, & &1.id)
      remaining = Enum.reject(sorted, &MapSet.member?(ttl_expired_ids, &1.id))
      count_excess = expired_by_max_count(remaining, class)

      # Union: TTL-expired records + count-excess records (deduped by id)
      all_expired =
        (ttl_expired ++ count_excess)
        |> Enum.uniq_by(& &1.id)
        |> Enum.sort_by(& &1.created_at, DateTime)

      {:ok, all_expired}
    end
  end

  @doc """
  Runs full retention enforcement for a data type across all records.

  Calls the store's list function, evaluates which records are expired,
  and deletes them. Returns `{:ok, deleted_count}` on success.

  ## Audit protection

  This function **never** touches audit-protected or permanent records.
  It only deletes transient and normal data that exceeds policy limits.

  ## Options

  - `:store` — store adapter module (default: configured adapter)
  - `:policy` — retention policy (default: loaded from config)
  - `:store_fun` — function to list records: `(store, session_id, opts) -> {:ok, [map()]}`
  - `:delete_fun` — function to delete a record: `(store, id, opts) -> {:ok, :ok}`
  - `:session_id` — optional session filter (nil = all sessions)

  ## Examples

      iex> store = Tet.Store.Memory
      iex> Tet.Store.Memory.start_link([])
      iex> policy = elem(Tet.Retention.Policy.new(
      ...>   classes: [checkpoint: [ttl_seconds: 0]]
      ...> ), 1)
      iex> Tet.Retention.Enforcer.enforce(policy, store, :checkpoint,
      ...>   store_fun: fn s, _sid, _o -> {:ok, []} end,
      ...>   delete_fun: fn _s, _id, _o -> {:ok, :ok} end)
      {:ok, 0}
  """
  @spec enforce(Policy.t(), module(), Policy.data_type(), keyword()) ::
          {:ok, non_neg_integer()} | {:error, term()}
  def enforce(%Policy{} = policy, store, data_type, opts \\ [])
      when is_atom(store) and is_atom(data_type) and is_list(opts) do
    # Skip audit-protected data types — they are never automatically pruned.
    if Policy.audit_protected?(policy, data_type) do
      {:ok, 0}
    else
      do_enforce(policy, store, data_type, opts)
    end
  end

  @doc """
  Returns a human-readable summary of the policy configuration for a data type.

  ## Examples

      iex> policy = elem(Tet.Retention.Policy.new([]), 1)
      iex> Tet.Retention.Enforcer.describe(policy, :checkpoint)
      "checkpoint → transient: TTL=86400s, max_count=1000, auto-deletable"

      iex> Tet.Retention.Enforcer.describe(policy, :approval)
      "approval → permanent: no TTL, unlimited count, audit-protected"
  """
  @spec describe(Policy.t(), Policy.data_type()) :: String.t()
  def describe(%Policy{} = policy, data_type) when is_atom(data_type) do
    class = Policy.class_for(policy, data_type)
    ttl_desc = if class.ttl_seconds, do: "TTL=#{class.ttl_seconds}s", else: "no TTL"
    count_desc = if class.max_count, do: "max_count=#{class.max_count}", else: "unlimited count"

    deletable =
      if Policy.audit_protected?(policy, data_type), do: "audit-protected", else: "auto-deletable"

    "#{data_type} → #{class.name}: #{ttl_desc}, #{count_desc}, #{deletable}"
  end

  # -- Private helpers --

  defp class_for(policy, data_type) do
    Policy.class_for(policy, data_type)
  end

  defp expired_by_ttl(_records, %Class{ttl_seconds: nil}, _now), do: []

  defp expired_by_ttl(records, %Class{ttl_seconds: ttl}, now) when is_integer(ttl) do
    cutoff = DateTime.add(now, -ttl, :second)

    Enum.filter(records, fn record ->
      case record do
        %{created_at: %DateTime{} = created_at} ->
          DateTime.compare(created_at, cutoff) == :lt

        %{created_at: created_at} when is_binary(created_at) ->
          case DateTime.from_iso8601(created_at) do
            {:ok, dt, _} -> DateTime.compare(dt, cutoff) == :lt
            _ -> false
          end

        _ ->
          false
      end
    end)
  end

  defp expired_by_max_count(_records, %Class{max_count: nil}), do: []

  defp expired_by_max_count(records, %Class{max_count: max_count}) when is_integer(max_count) do
    count = length(records)

    if count > max_count do
      # Records are sorted oldest-first. Drop the newest (excess) count and
      # return the oldest ones beyond the limit.
      excess = count - max_count

      records
      |> Enum.map(&normalize_created_at/1)
      |> Enum.sort_by(& &1.created_at, DateTime)
      |> Enum.take(excess)
    else
      []
    end
  end

  defp normalize_created_at(%{created_at: %DateTime{} = dt} = record) do
    %{record | created_at: dt}
  end

  defp normalize_created_at(%{created_at: iso_str} = record) when is_binary(iso_str) do
    case DateTime.from_iso8601(iso_str) do
      {:ok, dt, _} -> %{record | created_at: dt}
      _ -> %{record | created_at: DateTime.from_unix!(0)}
    end
  end

  defp normalize_created_at(record) do
    %{record | created_at: DateTime.from_unix!(0)}
  end

  defp verify_ack_token(policy, data_type, record_id, token) do
    with {:ok, raw} <- Base.url_decode64(token),
         parts when length(parts) == 4 <- String.split(raw, "|"),
         [nonce, timestamp, actor, _hmac] <- parts do
      expected =
        Policy.generate_ack_token(policy, data_type, record_id,
          nonce: nonce,
          timestamp: timestamp,
          actor: actor
        )

      if token == expected do
        :ok
      else
        {:error, :invalid_ack_token}
      end
    else
      _ -> {:error, :invalid_ack_token}
    end
  end

  defp do_enforce(policy, store, data_type, opts) do
    store_fun = Keyword.get(opts, :store_fun)
    delete_fun = Keyword.get(opts, :delete_fun)
    session_id = Keyword.get(opts, :session_id)

    if is_nil(store_fun) or is_nil(delete_fun) do
      {:error, :missing_store_or_delete_function}
    else
      with {:ok, records} <- store_fun.(store, session_id, []),
           {:ok, expired} <- expired_records(policy, data_type, records) do
        delete_results =
          expired
          |> Enum.map(fn record ->
            case delete_fun.(store, record.id, []) do
              {:ok, _} -> :ok
              {:error, reason} -> {:error, record.id, reason}
            end
          end)

        errors = Enum.filter(delete_results, &match?({:error, _, _}, &1))
        deleted_count = Enum.count(delete_results, &(&1 == :ok))

        case errors do
          [] -> {:ok, deleted_count}
          _ -> {:ok, deleted_count, errors}
        end
      end
    end
  end
end
