defmodule Tet.Compaction do
  @moduledoc """
  Pure compacted-context contract.

  Compaction is deliberately data-only: no provider calls, no persistence, and no
  background process pretending to be domain truth. It protects leading system
  prompts, a configurable recent-message window, and complete tool-call/result
  pairs before producing deterministic summary metadata suitable for prompt
  layers or runtime provider context.

  This implements the standalone slice of §12.8: compaction/pruning as a
  first-class subsystem with pre-flight history-shape safety.
  """

  alias Tet.Compaction.ToolPairs
  alias Tet.Prompt.Canonical

  @version "tet.compaction.v1"
  @default_max_messages 32
  @default_recent_count 8
  @default_strategy "deterministic_summary"
  @option_aliases %{
    "force" => :force,
    "id" => :id,
    "max_messages" => :max_messages,
    "min_compacted_count" => :min_compacted_count,
    "protected_recent_count" => :recent_count,
    "recent_count" => :recent_count,
    "recent_messages" => :recent_count,
    "strategy" => :strategy,
    "summary" => :summary
  }
  @enforce_keys [
    :changed?,
    :messages,
    :retained_messages,
    :compacted_messages,
    :compactions,
    :metadata
  ]
  defstruct [
    :id,
    :summary,
    changed?: false,
    messages: [],
    retained_messages: [],
    compacted_messages: [],
    compactions: [],
    metadata: %{}
  ]

  @type option ::
          {:force, boolean()}
          | {:id, binary()}
          | {:max_messages, non_neg_integer() | nil}
          | {:min_compacted_count, non_neg_integer()}
          | {:protected_recent_count, non_neg_integer()}
          | {:recent_count, non_neg_integer()}
          | {:recent_messages, non_neg_integer()}
          | {:strategy, atom() | binary()}
          | {:summary, binary()}

  @type options :: map() | [option()]

  @type compaction_layer :: %{
          required(:id) => binary(),
          required(:summary) => binary(),
          required(:source_message_ids) => [binary()],
          required(:strategy) => binary(),
          required(:original_message_count) => non_neg_integer(),
          required(:retained_message_count) => non_neg_integer(),
          required(:metadata) => map()
        }

  @type t :: %__MODULE__{
          id: binary() | nil,
          summary: binary() | nil,
          changed?: boolean(),
          messages: [Tet.Message.t()],
          retained_messages: [Tet.Message.t()],
          compacted_messages: [Tet.Message.t()],
          compactions: [compaction_layer()],
          metadata: map()
        }

  @doc "Returns the compaction contract version string."
  @spec version() :: binary()
  def version, do: @version

  @doc """
  Compacts an ordered message context while preserving protected boundaries.

  The returned `messages` field is provider-ready and includes a synthetic system
  summary message when compaction happened. `retained_messages` contains only
  original messages and is the right list to pass to `Tet.Prompt.build/1` with
  `compactions` when callers want a prompt compaction layer instead of a
  synthetic session message.
  """
  @spec compact([Tet.Message.t() | map()], options()) :: {:ok, t()} | {:error, term()}
  def compact(messages, opts \\ [])

  def compact(messages, opts) when is_list(messages) do
    with {:ok, normalized_opts} <- normalize_opts(opts),
         {:ok, messages} <- normalize_messages(messages),
         pair_index <- ToolPairs.index(messages),
         {:ok, plan} <- compaction_plan(messages, pair_index, normalized_opts),
         {:ok, result} <- build_result(messages, pair_index, plan, normalized_opts) do
      {:ok, result}
    end
  end

  def compact(_messages, _opts), do: {:error, :invalid_compaction_messages}

  @doc "Returns original retained messages for prompt-layer compaction input."
  @spec to_prompt_messages(t()) :: [Tet.Message.t()]
  def to_prompt_messages(%__MODULE__{retained_messages: messages}), do: messages

  @doc "Returns provider-ready messages, including a synthetic summary when compacted."
  @spec to_provider_messages(t()) :: [Tet.Message.t()]
  def to_provider_messages(%__MODULE__{messages: messages}), do: messages

  @doc "Returns prompt compaction layers generated by this result."
  @spec to_prompt_compactions(t()) :: [compaction_layer()]
  def to_prompt_compactions(%__MODULE__{compactions: compactions}), do: compactions

  defp normalize_opts(opts) when is_map(opts) do
    opts
    |> Map.to_list()
    |> normalize_opts()
  end

  defp normalize_opts(opts) when is_list(opts) do
    defaults = %{
      force?: false,
      id: nil,
      max_messages: @default_max_messages,
      min_compacted_count: 1,
      recent_count: @default_recent_count,
      strategy: @default_strategy,
      summary: nil
    }

    opts
    |> Enum.reduce_while({:ok, defaults}, fn
      {key, value}, {:ok, acc} ->
        with {:ok, normalized_key} <- normalize_option_key(key),
             {:ok, normalized_value} <- normalize_option_value(normalized_key, value) do
          {:cont, {:ok, Map.put(acc, normalized_key, normalized_value)}}
        else
          {:error, reason} -> {:halt, {:error, reason}}
        end

      _other, _acc ->
        {:halt, {:error, :invalid_compaction_options}}
    end)
  end

  defp normalize_opts(_opts), do: {:error, :invalid_compaction_options}

  defp normalize_option_key(:force), do: {:ok, :force?}

  defp normalize_option_key(key) when is_atom(key) do
    key
    |> Atom.to_string()
    |> normalize_option_key()
  end

  defp normalize_option_key(key) when is_binary(key) do
    case Map.fetch(@option_aliases, key) do
      {:ok, :force} -> {:ok, :force?}
      {:ok, normalized} -> {:ok, normalized}
      :error -> {:error, {:unknown_compaction_option, key}}
    end
  end

  defp normalize_option_key(key), do: {:error, {:unknown_compaction_option, key}}

  defp normalize_option_value(:force?, value) when is_boolean(value), do: {:ok, value}

  defp normalize_option_value(:id, nil), do: {:ok, nil}
  defp normalize_option_value(:id, value) when is_binary(value) and value != "", do: {:ok, value}

  defp normalize_option_value(:max_messages, nil), do: {:ok, nil}

  defp normalize_option_value(:max_messages, value) when is_integer(value) and value >= 0,
    do: {:ok, value}

  defp normalize_option_value(:min_compacted_count, value) when is_integer(value) and value >= 0,
    do: {:ok, value}

  defp normalize_option_value(:recent_count, value) when is_integer(value) and value >= 0,
    do: {:ok, value}

  defp normalize_option_value(:strategy, value) when is_atom(value),
    do: normalize_option_value(:strategy, Atom.to_string(value))

  defp normalize_option_value(:strategy, value) when is_binary(value) and value != "",
    do: {:ok, value}

  defp normalize_option_value(:summary, nil), do: {:ok, nil}

  defp normalize_option_value(:summary, value) when is_binary(value) and value != "",
    do: {:ok, value}

  defp normalize_option_value(key, _value), do: {:error, {:invalid_compaction_option, key}}

  defp normalize_messages(messages) do
    messages
    |> Enum.with_index()
    |> Enum.reduce_while({:ok, []}, fn {message, index}, {:ok, acc} ->
      case normalize_message(message, index) do
        {:ok, normalized} -> {:cont, {:ok, [normalized | acc]}}
        {:error, reason} -> {:halt, {:error, reason}}
      end
    end)
    |> case do
      {:ok, normalized} -> {:ok, Enum.reverse(normalized)}
      {:error, reason} -> {:error, reason}
    end
  end

  defp normalize_message(%Tet.Message{} = message, _index), do: {:ok, message}

  defp normalize_message(message, index) when is_map(message) do
    case Tet.Message.new(message) do
      {:ok, normalized} -> {:ok, normalized}
      {:error, reason} -> {:error, {:invalid_compaction_message, index, reason}}
    end
  end

  defp normalize_message(_message, index), do: {:error, {:invalid_compaction_message, index}}

  defp compaction_plan(messages, pair_index, opts) do
    count = length(messages)
    head_count = leading_system_count(messages)
    initial_split = initial_split(count, head_count, opts.recent_count)
    final_split = adjusted_split(messages, pair_index.pairs, initial_split, head_count)
    compacted_count = max(final_split - head_count, 0)
    changed? = compact?(count, compacted_count, opts)

    {:ok,
     %{
       changed?: changed?,
       compacted_count: compacted_count,
       final_split: final_split,
       head_count: head_count,
       initial_split: initial_split
     }}
  end

  defp compact?(count, compacted_count, opts) do
    over_threshold? = opts.force? or is_nil(opts.max_messages) or count > opts.max_messages
    over_threshold? and compacted_count >= opts.min_compacted_count and compacted_count > 0
  end

  defp build_result(messages, pair_index, %{changed?: false} = plan, opts) do
    with {:ok, metadata} <- metadata(messages, [], messages, pair_index, plan, opts) do
      {:ok,
       %__MODULE__{
         changed?: false,
         messages: messages,
         retained_messages: messages,
         compacted_messages: [],
         compactions: [],
         metadata: metadata
       }}
    end
  end

  defp build_result(messages, pair_index, %{changed?: true} = plan, opts) do
    compacted = Enum.slice(messages, plan.head_count, plan.final_split - plan.head_count)
    retained = Enum.take(messages, plan.head_count) ++ Enum.drop(messages, plan.final_split)

    with {:ok, metadata} <- metadata(messages, compacted, retained, pair_index, plan, opts),
         summary <- opts.summary || summary_text(metadata),
         id <- opts.id || generated_id(summary, metadata),
         {:ok, summary_message} <- summary_message(id, summary, messages, compacted, metadata) do
      compaction = %{
        id: id,
        summary: summary,
        source_message_ids: Enum.map(compacted, & &1.id),
        strategy: opts.strategy,
        original_message_count: length(messages),
        retained_message_count: length(retained),
        metadata: metadata
      }

      {:ok,
       %__MODULE__{
         id: id,
         summary: summary,
         changed?: true,
         messages:
           Enum.take(messages, plan.head_count) ++
             [summary_message] ++ Enum.drop(messages, plan.final_split),
         retained_messages: retained,
         compacted_messages: compacted,
         compactions: [compaction],
         metadata: metadata
       }}
    end
  end

  defp leading_system_count(messages) do
    Enum.reduce_while(messages, 0, fn
      %Tet.Message{role: :system}, count -> {:cont, count + 1}
      _message, count -> {:halt, count}
    end)
  end

  defp initial_split(count, head_count, recent_count) do
    tail_start = count - min(recent_count, max(count - head_count, 0))
    max(head_count, tail_start)
  end

  defp adjusted_split(messages, pairs, split, head_count) do
    new_split =
      split
      |> protect_system_after_head(messages, head_count)
      |> protect_crossing_pairs(pairs, head_count)

    if new_split == split do
      split
    else
      adjusted_split(messages, pairs, new_split, head_count)
    end
  end

  defp protect_system_after_head(split, messages, head_count) do
    messages
    |> Enum.with_index()
    |> Enum.find_value(split, fn
      {%Tet.Message{role: :system}, index} when index >= head_count and index < split -> index
      _other -> false
    end)
  end

  defp protect_crossing_pairs(split, pairs, head_count) do
    pairs
    |> Enum.filter(&pair_crosses_split?(&1, split, head_count))
    |> Enum.map(&max(head_count, ToolPairs.min_index(&1)))
    |> Enum.min(fn -> split end)
  end

  defp pair_crosses_split?(pair, split, head_count) do
    has_compacted_side? = Enum.any?(pair.indexes, &(&1 >= head_count and &1 < split))
    has_retained_side? = Enum.any?(pair.indexes, &(&1 < head_count or &1 >= split))
    has_compacted_side? and has_retained_side?
  end

  defp metadata(messages, compacted, retained, pair_index, plan, opts) do
    metadata = %{
      compacted_count: length(compacted),
      compacted_message_count: length(compacted),
      compacted_message_ids: Enum.map(compacted, & &1.id),
      compacted_range: compacted_range_metadata(messages, compacted, plan),
      contract_version: @version,
      noop_reason: noop_reason(messages, plan, opts),
      options: options_metadata(opts),
      original_count: length(messages),
      original_message_count: length(messages),
      original_range: range_metadata(messages, 0, length(messages) - 1),
      protected: protected_metadata(plan, opts),
      protected_tool_pairs: protected_tool_pairs(pair_index.pairs, plan),
      retained_count: length(retained),
      retained_message_count: length(retained),
      retained_message_ids: Enum.map(retained, & &1.id),
      retained_ranges: retained_ranges(messages, plan),
      strategy: opts.strategy,
      tool_pairs: tool_pairs_metadata(pair_index.pairs, plan),
      orphaned_tool_calls: orphaned_metadata(pair_index.orphaned_calls, :call),
      orphaned_tool_results: orphaned_metadata(pair_index.orphaned_results, :result)
    }

    Canonical.normalize(metadata)
  end

  defp noop_reason(_messages, %{changed?: true}, _opts), do: nil

  defp noop_reason(messages, %{compacted_count: compacted_count}, opts) do
    over_threshold? =
      opts.force? or is_nil(opts.max_messages) or length(messages) > opts.max_messages

    cond do
      not over_threshold? -> :below_max_messages
      compacted_count == 0 -> :nothing_to_compact
      true -> :below_min_compacted_count
    end
  end

  defp options_metadata(opts) do
    %{
      force: opts.force?,
      max_messages: opts.max_messages,
      min_compacted_count: opts.min_compacted_count,
      recent_count: opts.recent_count
    }
  end

  defp protected_metadata(plan, opts) do
    %{
      adjusted_recent_start_index: plan.final_split,
      leading_system_count: plan.head_count,
      requested_recent_count: opts.recent_count,
      requested_recent_start_index: plan.initial_split
    }
  end

  defp protected_tool_pairs(pairs, plan) do
    pairs
    |> Enum.filter(
      &(pair_location(&1, plan) == :retained and ToolPairs.min_index(&1) < plan.initial_split)
    )
    |> Enum.map(fn pair ->
      reason =
        if pair_crosses_split?(pair, plan.initial_split, plan.head_count),
          do: :split_boundary,
          else: :retained_after_split_adjustment

      pair_metadata(pair, :retained, reason)
    end)
  end

  defp tool_pairs_metadata(pairs, plan) do
    Enum.map(pairs, fn pair ->
      pair_metadata(pair, pair_location(pair, plan), nil)
    end)
  end

  defp pair_location(pair, plan) do
    if Enum.any?(pair.indexes, &(&1 >= plan.head_count and &1 < plan.final_split)) do
      :compacted
    else
      :retained
    end
  end

  defp pair_metadata(pair, location, nil) do
    %{
      call_indexes: pair.call_indexes,
      call_message_ids: pair.call_message_ids,
      location: location,
      result_indexes: pair.result_indexes,
      result_message_ids: pair.result_message_ids,
      tool_call_id: pair.tool_call_id
    }
  end

  defp pair_metadata(pair, location, reason) do
    pair
    |> pair_metadata(location, nil)
    |> Map.put(:reason, reason)
  end

  defp orphaned_metadata(orphans, kind) do
    Enum.map(orphans, fn orphan ->
      %{
        indexes: Map.fetch!(orphan, :indexes),
        kind: kind,
        message_ids: Map.fetch!(orphan, :message_ids),
        tool_call_id: Map.fetch!(orphan, :tool_call_id)
      }
    end)
  end

  defp range_metadata(_messages, start_index, end_index) when start_index > end_index, do: nil

  defp range_metadata(messages, start_index, end_index) do
    first = Enum.at(messages, start_index)
    last = Enum.at(messages, end_index)

    %{
      first_index: start_index,
      first_message_id: message_id(first),
      last_index: end_index,
      last_message_id: message_id(last)
    }
  end

  defp compacted_range_metadata(_messages, [], _plan), do: nil

  defp compacted_range_metadata(messages, _compacted, plan) do
    range_metadata(messages, plan.head_count, plan.final_split - 1)
  end

  defp retained_ranges(messages, %{changed?: false}) do
    [range_metadata(messages, 0, length(messages) - 1)]
    |> Enum.reject(&is_nil/1)
  end

  defp retained_ranges(messages, plan) do
    count = length(messages)

    [
      range_metadata(messages, 0, plan.head_count - 1),
      range_metadata(messages, plan.final_split, count - 1)
    ]
    |> Enum.reject(&is_nil/1)
  end

  defp summary_text(metadata) do
    compacted = Map.fetch!(metadata, "compacted_message_count")
    original = Map.fetch!(metadata, "original_message_count")
    retained = Map.fetch!(metadata, "retained_message_count")
    strategy = Map.fetch!(metadata, "strategy")
    protected_pairs = metadata |> Map.fetch!("protected_tool_pairs") |> length()
    range = Map.fetch!(metadata, "compacted_range")

    range_text =
      case range do
        nil ->
          "no message range"

        %{"first_message_id" => first_id, "last_message_id" => last_id} ->
          "#{first_id}..#{last_id}"
      end

    "Compacted #{compacted} earlier messages (#{range_text}) using #{strategy}; " <>
      "retained #{retained}/#{original} messages and protected #{protected_pairs} tool pair(s)."
  end

  defp generated_id(summary, metadata) do
    source = %{metadata: metadata, summary: summary, version: @version}
    "compaction-" <> hash_prefix(source)
  end

  defp summary_message(id, summary, messages, compacted, metadata) do
    session_id = messages |> List.first() |> Map.fetch!(:session_id)
    timestamp = compacted |> List.last() |> Map.get(:timestamp, List.first(messages).timestamp)

    Tet.Message.new(%{
      id: "message-" <> id,
      session_id: session_id,
      role: :system,
      content: summary,
      timestamp: timestamp,
      metadata: %{
        compaction_contract_version: @version,
        compaction_id: id,
        compaction_metadata: metadata
      }
    })
  end

  defp hash_prefix(value) do
    {:ok, normalized} = Canonical.normalize(value)

    normalized
    |> Canonical.hash()
    |> String.slice(0, 16)
  end

  defp message_id(nil), do: nil
  defp message_id(%Tet.Message{id: id}), do: id
end
