defmodule Tet.CLI.Completion do
  @moduledoc """
  Shell completion script generator for tet CLI commands.

  Generates completion scripts for bash, zsh, and fish shells.
  Completions are purely additive UX — they do not alter runtime policy
  or logic in any way.
  """

  @commands %{
    "ask" => %{
      description: "Stream a reply and persist the chat turn",
      subcommands: [],
      options: ["--session"]
    },
    "events" => %{
      description: "Show the read-only runtime event timeline",
      subcommands: [],
      options: ["--session"]
    },
    "timeline" => %{
      description: "Alias for `tet events`",
      subcommands: [],
      options: ["--session"]
    },
    "profiles" => %{
      description: "List configured agent profiles",
      subcommands: [],
      options: []
    },
    "profile" => %{
      description: "Inspect one configured agent profile",
      subcommands: ["show"],
      options: []
    },
    "sessions" => %{
      description: "List persisted sessions",
      subcommands: [],
      options: []
    },
    "session" => %{
      description: "Show a session and its messages",
      subcommands: ["show"],
      options: []
    },
    "doctor" => %{
      description: "Check config/store/provider/release health",
      subcommands: [],
      options: []
    },
    "help" => %{
      description: "Show help",
      subcommands: [],
      options: []
    },
    "completion" => %{
      description: "Generate shell completion scripts",
      subcommands: ["bash", "zsh", "fish"],
      options: []
    },
    "history" => %{
      description: "Search prompt history",
      subcommands: ["search"],
      options: ["--fuzzy", "--limit"]
    },
    "prompt-lab" => %{
      description: "Refine prompts and explore quality dimensions",
      subcommands: ["refine", "presets", "dimensions"],
      options: ["--preset", "--json"]
    },
    "correct" => %{
      description: "Suggest safer command alternatives",
      subcommands: [],
      options: ["--json"]
    }
  }

  @doc "Returns the command map used by completion generators."
  @spec commands() :: map()
  def commands, do: @commands

  @doc "Returns sorted list of top-level command names."
  @spec command_names() :: [String.t()]
  def command_names, do: @commands |> Map.keys() |> Enum.sort()

  @doc "Generates a completion script for the given shell."
  @spec generate(String.t()) :: {:ok, String.t()} | {:error, term()}
  def generate(shell) when shell in ["bash", "zsh", "fish"] do
    script = apply(__MODULE__, String.to_atom("generate_#{shell}"), [])
    {:ok, script}
  end

  def generate(shell), do: {:error, {:unsupported_shell, shell}}

  @doc "Generates bash completion script."
  @spec generate_bash() :: String.t()
  def generate_bash do
    cmds = command_names() |> Enum.join(" ")

    profile_sub = @commands["profile"].subcommands |> Enum.join(" ")
    session_sub = @commands["session"].subcommands |> Enum.join(" ")
    completion_sub = @commands["completion"].subcommands |> Enum.join(" ")
    history_sub = @commands["history"].subcommands |> Enum.join(" ")
    prompt_lab_sub = @commands["prompt-lab"].subcommands |> Enum.join(" ")

    """
    #!/usr/bin/env bash
    # tet bash completion — generated by tet completion bash
    # UX only: does not alter runtime policy

    _tet_completions() {
      local cur prev words cword
      _init_completion -n || return

      case ${prev} in
        tet)
          COMPREPLY=($(compgen -W '#{cmds}' -- "${cur}"))
          ;;
        profile)
          COMPREPLY=($(compgen -W '#{profile_sub}' -- "${cur}"))
          ;;
        session)
          COMPREPLY=($(compgen -W '#{session_sub}' -- "${cur}"))
          ;;
        completion)
          COMPREPLY=($(compgen -W '#{completion_sub}' -- "${cur}"))
          ;;
        history)
          COMPREPLY=($(compgen -W '#{history_sub}' -- "${cur}"))
          ;;
        prompt-lab)
          COMPREPLY=($(compgen -W '#{prompt_lab_sub}' -- "${cur}"))
          ;;
        --session)
          COMPREPLY=()
          ;;
        --limit)
          COMPREPLY=()
          ;;
        --fuzzy)
          COMPREPLY=()
          ;;
        --preset)
          COMPREPLY=()
          ;;
        *)
          # Offer options when cursor is on a flag
          if [[ ${cur} == --* ]]; then
            local opts=""
            case ${words[1]} in
              ask|events|timeline) opts="--session" ;;
              history) opts="--fuzzy --limit" ;;
              prompt-lab) opts="--preset --json" ;;
              correct) opts="--json" ;;
            esac
            COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
          fi
          ;;
      esac
    }

    complete -F _tet_completions tet
    """
    |> String.trim_trailing()
  end

  @doc "Generates zsh completion script."
  @spec generate_zsh() :: String.t()
  def generate_zsh do
    command_lines =
      @commands
      |> Enum.sort_by(fn {name, _} -> name end)
      |> Enum.map(fn {name, cmd} ->
        subcmd_part =
          case Map.get(cmd, :subcommands, []) do
            [] -> ""
            subs -> ":{#{Enum.join(subs, ",")}}"
          end

        "        '#{name}:#{cmd.description}#{subcmd_part}'"
      end)
      |> Enum.join("\n")

    """
    #compdef tet
    # tet zsh completion — generated by tet completion zsh
    # UX only: does not alter runtime policy

    _tet() {
      local -a commands
      commands=(
    #{command_lines}
      )

      _arguments -C \\
        '1: :->command' \\
        '*::arg:->argument'

      case $state in
        command)
          _describe 'tet command' commands
          ;;
        argument)
          case $words[2] in
            ask|events|timeline)
              _arguments \\
                '--session[Session id]:session id:' \\
                '*:prompt:'
              ;;
            profile)
              _describe 'profile subcommand' '(show:Inspect a profile)'
              ;;
            session)
              _describe 'session subcommand' '(show:Show a session)'
              ;;
            completion)
              _describe 'completion shell' '(bash:bash completion)(zsh:zsh completion)(fish:fish completion)'
              ;;
            history)
              _describe 'history subcommand' '(search:Search prompt history)' \\
                '--fuzzy[Fuzzy search mode]' \\
                '--limit[Max results]:limit:'
              ;;
            prompt-lab)
              _describe 'prompt-lab subcommand' '(refine:Refine a prompt)(presets:List presets)(dimensions:List quality dimensions)' \\
                '--preset[Preset id]:preset:' \\
                '--json[JSON output]'
              ;;
            correct)
              _arguments \\
                '--json[JSON output]' \\
                '*:command:'
              ;;
          esac
          ;;
      esac
    }

    _tet
    """
    |> String.trim_trailing()
  end

  @doc "Generates fish completion script."
  @spec generate_fish() :: String.t()
  def generate_fish do
    command_lines =
      @commands
      |> Enum.sort_by(fn {name, _} -> name end)
      |> Enum.map(fn {name, cmd} ->
        "complete -c tet -n '__fish_use_subcommand' -a '#{name}' -d '#{cmd.description}'"
      end)
      |> Enum.join("\n")

    option_lines =
      @commands
      |> Enum.filter(fn {_, cmd} -> Map.get(cmd, :options, []) != [] end)
      |> Enum.flat_map(fn {name, cmd} ->
        Enum.map(Map.get(cmd, :options, []), fn opt ->
          "complete -c tet -n '__fish_seen_subcommand_from #{name}' -l #{String.trim_leading(opt, "--")} -d 'Option'"
        end)
      end)
      |> Enum.join("\n")

    subcommand_lines =
      @commands
      |> Enum.filter(fn {_, cmd} -> Map.get(cmd, :subcommands, []) not in [nil, []] end)
      |> Enum.flat_map(fn {name, cmd} ->
        Enum.map(Map.get(cmd, :subcommands, []), fn sub ->
          "complete -c tet -n '__fish_seen_subcommand_from #{name}' -a '#{sub}'"
        end)
      end)
      |> Enum.join("\n")

    """
    # tet fish completion — generated by tet completion fish
    # UX only: does not alter runtime policy

    #{command_lines}
    #{subcommand_lines}
    #{option_lines}
    """
    |> String.trim_trailing()
  end
end
